"""High-Level Network Emulator Interface for Connected Vehicle Telemetry.

Connects the vehicle simulation layer to the network impairment pipeline,
converting telemetry frames into network packets, tracking AoI, and providing
comprehensive communication performance statistics.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional
from network.models import DeliveryStatus, NetworkPacket
from network.network_config import NetworkConfig
from network.packet_queue import PacketQueue
from simulator.sensor_generator import TelemetryPacket


class NetworkEmulator:
    """High-level facade orchestrating transmission, impairment, delivery, and AoI freshness tracking."""

    def __init__(self, config: Optional[NetworkConfig] = None) -> None:
        self.config = config or NetworkConfig()
        self.config.validate()
        self.queue = PacketQueue(config=self.config)

        self._seq_counters: Dict[str, int] = {}
        self._packet_id_counter: int = 0
        self._total_telemetry_frames_ingested: int = 0

    def _next_seq(self, sensor_name: str) -> int:
        """Increment and return monotonically increasing sequence number for a sensor channel."""
        seq = self._seq_counters.get(sensor_name, 1)
        self._seq_counters[sensor_name] = seq + 1
        return seq

    def _next_packet_id(self) -> str:
        """Generate unique string packet identifier."""
        self._packet_id_counter += 1
        return f"pkt_{self._packet_id_counter:06d}"

    def ingest_telemetry_frame(
        self,
        telemetry: TelemetryPacket,
        current_time: float,
        split_channels: bool = True,
    ) -> List[Optional[NetworkPacket]]:
        """Ingest a vehicle telemetry frame and submit corresponding packets into the network pipeline.
        
        Args:
            telemetry: Telemetry frame generated by the vehicle simulator.
            current_time: Current simulation timestamp in seconds.
            split_channels: If True, each sensor is transmitted as a discrete packet;
                           If False, the entire frame is bundled into a single packet.
                           
        Returns:
            List of scheduled NetworkPacket objects (or None for dropped packets).
        """
        self._total_telemetry_frames_ingested += 1
        scheduled_packets: List[Optional[NetworkPacket]] = []

        if split_channels:
            # Transmit individual sensor channels independently
            sensor_fields = [
                ("speed_kmh", telemetry.speed_kmh, 32),
                ("rpm", telemetry.rpm, 32),
                ("engine_load", telemetry.engine_load, 32),
                ("engine_temperature_c", telemetry.engine_temperature_c, 32),
                ("cooling_fan_status", telemetry.cooling_fan_status, 16),
            ]

            for s_name, s_val, s_size in sensor_fields:
                if s_val is not None:  # Skip dropped sensor values (e.g. MISSING_SENSOR_DATA)
                    pkt = NetworkPacket(
                        packet_id=self._next_packet_id(),
                        vehicle_id=telemetry.vehicle_id,
                        sensor_name=s_name,
                        value=s_val,
                        generation_timestamp=current_time,
                        sequence_number=self._next_seq(s_name),
                        size_bytes=s_size,
                    )
                    res = self.queue.enqueue(pkt, current_time=current_time)
                    scheduled_packets.append(res)
        else:
            # Single bundled telemetry packet
            bundle_pkt = NetworkPacket(
                packet_id=self._next_packet_id(),
                vehicle_id=telemetry.vehicle_id,
                sensor_name="full_telemetry_bundle",
                value=telemetry.to_dict(),
                generation_timestamp=current_time,
                sequence_number=self._next_seq("full_telemetry_bundle"),
                size_bytes=144,
            )
            res = self.queue.enqueue(bundle_pkt, current_time=current_time)
            scheduled_packets.append(res)

        return scheduled_packets

    def advance_time(self, current_time: float) -> List[NetworkPacket]:
        """Advance network simulation time and pop all delivered packets arrived by current_time."""
        return self.queue.advance_time(current_time)

    def get_current_aoi(self, vehicle_id: str, sensor_name: str, current_time: float) -> Optional[float]:
        """Query instantaneous Age of Information freshness for a specific sensor stream."""
        return self.queue.aoi_tracker.get_current_aoi(vehicle_id, sensor_name, current_time)

    def get_performance_summary(self, current_time: Optional[float] = None) -> Dict[str, Any]:
        """Compile comprehensive communication performance, loss, and freshness report."""
        return {
            "total_frames_ingested": self._total_telemetry_frames_ingested,
            "packets_in_transit": self.queue.pending_count(),
            "packets_delivered": self.queue.delivered_count(),
            "packets_dropped": self.queue.dropped_count(),
            "packet_loss_rate_percent": round(
                (self.queue.dropped_count() / max(1, self.queue.delivered_count() + self.queue.dropped_count())) * 100.0, 2
            ),
            "scheduler_metrics": self.queue.get_scheduler_metrics(),
            "aoi_statistics": self.queue.aoi_tracker.get_all_statistics(current_time),
        }

    def reset(self, new_seed: Optional[int] = None) -> None:
        """Reset emulator pipeline, sequences, and AoI trackers."""
        self._seq_counters.clear()
        self._packet_id_counter = 0
        self._total_telemetry_frames_ingested = 0
        self.queue.reset(new_seed)
